# Generated by Django 2.1.3 on 2020-07-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiosLatestQueryForMe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BIOS_Package_Me',
        ),
    ]
