# Generated by Django 2.0.7 on 2018-07-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=30)),
                ('Version', models.CharField(max_length=20)),
                ('TestTime', models.DateTimeField(auto_now_add=True)),
                ('ReportFile', models.FileField(upload_to='./upload/')),
            ],
        ),
    ]
