# Generated by Django 2.0.7 on 2018-09-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SW_InventoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('CollectTime', models.DateTimeField(auto_now_add=True)),
                ('ReportFile', models.FileField(upload_to='./upload/')),
            ],
        ),
    ]
