# Generated by Django 2.0.7 on 2018-11-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EngineerName', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamManager', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='engineerinfo',
            name='EngineerManager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ids', to='EngineerInfo.Managers'),
        ),
    ]
