# Generated by Django 2.0.7 on 2018-07-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiosUpload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bios_package',
            name='PackageType',
            field=models.CharField(default='PKG', max_length=5),
        ),
    ]
