# Generated by Django 2.0.7 on 2018-09-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiosUpload', '0003_bios_package_filenameref'),
    ]

    operations = [
        migrations.AddField(
            model_name='bios_package',
            name='BiosType',
            field=models.CharField(default='STD', max_length=5),
        ),
    ]
