# Generated by Django 2.0.7 on 2018-07-31 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductInfo', '0002_auto_20180731_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Family', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Product_Family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ids', to='ProductInfo.ProductFamily'),
        ),
    ]
