# Generated by Django 2.0.7 on 2018-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiosUpload', '0002_bios_package_packagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bios_package',
            name='FileNameRef',
            field=models.CharField(default='', max_length=30),
        ),
    ]
