# Generated by Django 2.0.7 on 2018-09-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiosUpload', '0005_auto_20180917_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bios_package',
            name='FileNameRef',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
