# Generated by Django 2.0.7 on 2018-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessGroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessgroup_info',
            name='Business_Group',
            field=models.CharField(default='EPM', max_length=20),
        ),
    ]
