# Generated by Django 2.0.7 on 2018-07-31 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessGroup', '0002_auto_20180731_1424'),
        ('ProductInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='Business_Group',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Business_Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ids', to='BusinessGroup.BusinessGroup_Info'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='ProductName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Product_Family',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Product_Family',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ProductFamily',
        ),
    ]
